### ISSUE TITLE
Add and delete Snap buttons

### ISSUE THREAD

**Issue by shepherdjerred** [ShepherdJerred-homework/snapper#8]

**Comment by acampb311** [comment]
Initial work is done with fb94f8b81271853de589c3661ae2f988a030e1c7

Context menus as well as keyboard shortcuts are still needed

**Comment by acampb311** [comment]
~~Yeah, context menus are not really a thing in UWP. ggwp~~
well, i need to get good

**Comment by acampb311** [comment]
see 362d7d45f8044868b8eeb7897df23e8348a8ece1
